default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rodolfopeixoto
  password: totalpass@rodolfopeixoto
  port: 5432
  host: localhost

development:
  <<: *default
  database: fretadao_development

test:
  <<: *default
  database: fretadao_test

production:
  <<: *default
  database: fretadao_production
  host: localhost
  username: <%= ENV['FRETADAO_DATABASE_USERNAME'] %>
  password: <%= ENV['FRETADAO_DATABASE_PASSWORD'] %>
