default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: master
  port: 5432
  host: db

development:
  <<: *default
  database: fretadao_development

test:
  <<: *default
  database: fretadao_test

production:
  <<: *default
  database: fretadao_production
  host: localhost
  username: <%= ENV['FRETADAO_DATABASE_USERNAME'] %>
  password: <%= ENV['FRETADAO_DATABASE_PASSWORD'] %>
